Repository prgrms-web-devcourse-final-project/WEB1_2_Child-Learn_FE, pull requests merged in 2024-12, with the labels that each got.

#48 [Feat] 카드 뒤집기 구현
  src/app/layout/Layout.tsx
  src/app/router/Router.tsx
  src/features/minigame/flipcardgame/lib/useFlipCardLogic.ts
  src/features/minigame/flipcardgame/model/filpCardStore.ts
  src/features/minigame/flipcardgame/types/cardTypes.ts
  src/features/minigame/flipcardgame/ui/Cards.tsx
  src/mocks/handler/flipCardGameHandlers.ts
  src/mocks/handler/index.ts
  src/pages/MiniGamePage/FlipCardGamePage/FlipCardGamePage.tsx
  src/pages/MiniGamePage/MiniGamePage.tsx
  src/shared/api/minigames.ts
Labels: ✨ Feature

#50 Feature/advanced chat/scrum 84
  package-lock.json
  package.json
  public/img/imagex.png
  public/img/pause.png
  public/img/play.png
  src/app/layout/Layout.tsx
  src/app/router/Router.tsx
  src/entities/stock/model/stockAd.ts
  src/entities/stock/types/index.ts
  src/entities/stock/types/stockAd.ts
  src/features/Advanced_chat/model/stockWebSocket.ts
  src/features/Advanced_chat/model/store/useAdvancedGameStore.ts
  src/features/Advanced_chat/types/game.ts
  src/features/Advanced_chat/types/stock.ts
  src/features/Advanced_chat/ui/AdvancedGame.tsx
  src/features/Advanced_chat/ui/Notice Modal/NoticeModal.tsx
  src/features/Advanced_chat/ui/StockChart/stockchart.tsx
  src/features/Advanced_chat/ui/StockChart/styled.ts
  src/features/Advanced_chat/ui/StockSlider/stockSlider.tsx
  src/features/Advanced_chat/ui/StockSlider/styled.ts
  src/features/Advanced_chat/ui/TradeModal/TradeModal.tsx
  src/features/Advanced_chat/ui/TradeModal/styled.ts
  src/features/Advanced_chat/ui/stockSlider.tsx
  src/features/Advanced_chat/ui/styled.ts
  src/features/Intermediate_chat/model/stock.ts
  src/features/Intermediate_chat/model/types/stock.ts
  src/features/Intermediate_chat/ui/StockSlider.tsx
  src/features/article/article.tsx
  src/features/beginner_chat/model/store/graph.store.ts
  src/features/beginner_chat/model/store/quiz.store.ts
  src/features/beginner_chat/model/types/graph.ts
  src/features/beginner_chat/model/types/quiz.ts
  src/features/beginner_chat/model/types/stock.ts
  src/features/beginner_chat/ui/fast-graph/fast-graph.tsx
  src/features/beginner_chat/ui/fast-navgation/fast-navigation.tsx
  src/features/beginner_chat/ui/quiz-widget/quizcard.tsx
  src/features/beginner_chat/ui/quiz-widget/quizpage.tsx
  src/mocks/browser.ts
  src/mocks/handler/IntermediateHandlers.ts
  src/mocks/handler/advancedHandlers.ts
  src/mocks/handler/beginnerHandlers.ts
  src/mocks/handler/index.ts
  src/pages/TradePages/AdvancedTradePage/AdvancedTradePage.tsx
  src/pages/TradePages/AdvancedTradePage/AdvancedTradeStyled.ts
  src/pages/TradePages/AdvancedTradePage/StockSlider.tsx
  src/pages/TradePages/IntermediateTradePage/IntermediatePage.tsx
  src/shared/api/advancedGame.ts
  src/shared/api/stock.ts
  src/shared/ui/Advanced/index.tsx
  src/shared/ui/Advanced/styled.ts
  src/shared/ui/Intermediate/StockChat.tsx
  src/shared/ui/PointBadge/PointBadge.tsx
Labels: 📚 Docs, ✨ Feature

#51 [Feat] 카드 뒤집기 구현
  src/features/minigame/flipcardgame/ui/Cards.tsx
  src/mocks/handler/wordQuizGameHandler.ts
  src/pages/MiniGamePage/MiniGamePage.tsx
Labels: ✨ Feature

#53 [Fix] 이미지 및 라우터 경로 수정
  public/icons/OX.png
  public/icons/gift.png
  public/icons/graph.png
  public/icons/smile.png
  public/icons/square.png
  public/img/Check.png
  public/img/book.png
  public/img/copy.png
  public/img/dollar.png
  public/img/file.png
  public/img/puzzle.png
  public/img/zoom.png
  src/app/router/Router.tsx
  src/features/mainpage/ui/DifficultyModal.tsx
Labels: 🐛 Fix

#58 [Fix] 카드 뒤집기 API 수정
  src/mocks/handler/flipCardGameHandlers.ts
  src/shared/api/minigames.ts
Labels: 🐛 Fix

#59 [Fix] 카드 목록 데이터타입 수정
  src/features/minigame/flipcardgame/lib/useFlipCardLogic.ts
  src/features/minigame/flipcardgame/model/filpCardStore.ts
  src/features/minigame/flipcardgame/types/cardTypes.ts
  src/features/minigame/flipcardgame/ui/Cards.tsx
  src/features/minigame/flipcardgame/ui/Timer.tsx
  src/mocks/handler/flipCardGameHandlers.ts
Labels: 🐛 Fix

#60 Fix: 동음이의어가 있을 경우를 막기 위해 단어의 설명이 일치할 경우에만 같은 단어로 매칭하도록 변경 #SCRUM-46
  src/pages/MiniGamePage/FlipCardGamePage/FlipCardGamePage.tsx
Labels: 🐛 Fix

#61 [fix] 초급 & 중급 그래프 api 수정
  src/features/Intermediate_chart/model/stock.ts
  src/features/beginner_chart/model/store/graph.store.ts
  src/shared/api/stock.ts
Labels: 🐛 Fix

#62 [fix] 중급 API 요청에 Authorization 헤더 추가 및 토큰정보 에러확인
  src/features/Advanced_chat/model/stockWebSocket.ts
  src/features/Intermediate_chart/model/stock.ts
Labels: 🐛 Fix

#63 [fix] 중급 API 요청에 토큰정보 들고오기 로직 추가
  src/features/Intermediate_chart/model/stock.ts
Labels: 🐛 Fix

#64 [Fix] 초급 토큰 들고오기 로직 추가
  src/features/beginner_chart/model/store/graph.store.ts
  src/features/beginner_chart/model/store/quiz.store.ts
  src/features/beginner_chart/model/types/quiz.ts
  src/features/beginner_chart/model/types/stock.ts
  src/features/beginner_chart/ui/quiz-widget/quizcard.tsx
  src/features/beginner_chart/ui/quiz-widget/quizpage.tsx
Labels: 🐛 Fix

#66 [Fix] 중급 그래프 수정
  src/features/Intermediate_chart/model/stock.ts
  src/features/Intermediate_chart/model/types/stock.ts
  src/features/Intermediate_chart/ui/StockSlider.tsx
  src/features/beginner_chart/model/store/graph.store.ts
  src/shared/api/stock.ts
Labels: 🐛 Fix

#67 [fix] 중급 그래프 수정 api 인증확인 추가
  src/shared/api/stock.ts
Labels: 🐛 Fix

#68 [Fix] 중급 그래프 수정 api 인증 수정
  src/entities/User/model/store/authStore.ts
  src/shared/api/stock.ts
Labels: 🐛 Fix

#69 [Feat] 검색 페이지 구현
  public/img/friend-mark.png
  src/app/router/Router.tsx
  src/features/search/api/userApi.ts
  src/features/search/lib/queries.ts
  src/features/search/lib/useDebounce.ts
  src/features/search/model/types.ts
  src/features/search/ui/SearchResultList.tsx
  src/mocks/handler/index.ts
  src/mocks/handler/searchHandlers.ts
  src/pages/searchPage/SearchPage.tsx
  src/shared/ui/SearchBar/SearchBar.tsx
Labels: ✨ Feature

#71 [Modify] 리프레쉬 토큰 로직 수정
  src/app/providers/withAuth.tsx
Labels: 🐛 Fix

#76 [Fix] 초급 그래프 수정
  src/app/layout/Layout.tsx
  src/app/router/Router.tsx
  src/features/beginner_chart/ui/fast-graph/fast-graph.tsx
  src/features/beginner_chart/ui/quiz-widget/quizpage.tsx
  src/pages/TradePages/BeginnerTradePage/BeginnerTradePage.tsx
  src/pages/TradePages/BeginnerTradePage/QuizGraphPage.tsx
Labels: 📚 Docs, 🐛 Fix

#77 [Fix] 초급 그래프 아티클 수정
  src/features/beginner_chart/ui/fast-graph/fast-graph.tsx
  src/features/beginner_chart/ui/fast-navgation/fast-navigation.tsx
  src/pages/TradePages/BeginnerTradePage/QuizGraphPage.tsx
Labels: 📚 Docs

#78 [Fix] 미니게임 성공 시 포인트를 받아오는 API 오류 수정
  src/features/minigame/points/types/pointTypes.ts
  src/mocks/handler/walletHandlers.ts
  src/pages/MiniGamePage/FlipCardGamePage/FlipCardGamePage.tsx
  src/pages/MiniGamePage/MiniGamePage.tsx
  src/shared/api/wallets.ts
Labels: 🐛 Fix

#79 [Fix] 초급 그래프 퀴즈 데이터 받아오기 수정
  src/features/beginner_chart/model/store/quiz.store.ts
Labels: 🐛 Fix

#80 [Fix] 초급 그래프 퀴즈 데이터 받아오기 수정2
  src/pages/TradePages/BeginnerTradePage/QuizGraphPage.tsx
Labels: 🐛 Fix

#81 [Modify] my-info api 로직 수정
  src/entities/User/lib/queries.ts
Labels: 🐛 Fix, ✨ Feature

#82 [Feat] 낱말 퀴즈 구현
  src/features/minigame/wordquizgame/model/wordQuizStore.ts
  src/features/minigame/wordquizgame/types/wordTypes.ts
  src/features/minigame/wordquizgame/ui/Header.tsx
  src/mocks/handler/index.ts
  src/mocks/handler/walletHandlers.ts
  src/mocks/handler/wordQuizGameHandler.ts
  src/pages/MiniGamePage/FlipCardGamePage/FlipCardGamePage.tsx
  src/pages/MiniGamePage/MiniGamePage.tsx
  src/pages/MiniGamePage/WordQuizGamePage/WordQuizGamePage.tsx
  src/pages/MiniGamePage/WordQuizGamePage/WordQuizResultPage.tsx
  src/shared/api/minigames.ts
Labels: ✨ Feature

#83 [Modify] 마이페이지 my-info 로직 수정
  src/features/mypage/lib/queries.ts
Labels: 🐛 Fix

#84 [Modify] 마이페이지 쿼리 수정
  src/features/mypage/lib/queries.ts
Labels: 🐛 Fix

#85 [Feat] 낱말 퀴즈 구현
  src/features/minigame/wordquizgame/ui/Header.tsx
  src/pages/MiniGamePage/MiniGamePage.tsx
  src/pages/MiniGamePage/WordQuizGamePage/WordQuizResultPage.tsx
Labels: ✨ Feature

#86 [Modify] 마이페이지 새로고침 로직 수정
  src/entities/User/lib/queries.ts
  src/features/mypage/lib/queries.ts
Labels: 🐛 Fix

#87 [Fix] 초급 그래프 포인트 받아오기 로직 수정
  src/features/beginner_chart/model/store/quiz.store.ts
  src/pages/TradePages/BeginnerTradePage/QuizGraphPage.tsx
Labels: 🐛 Fix

#88 [Fix] 낱말 퀴즈 플레이 가능함에도 접근 불가능한 버그 수정
  src/pages/MiniGamePage/MiniGamePage.tsx
Labels: 🐛 Fix

#89 [Modify] 마이페이지 직접 API 호출하는 로직 수정
  src/pages/myPage/MyPage.tsx
Labels: 🐛 Fix

#90 [Fix] 낱말 퀴즈 난이도별 플레이 여부 버그 수정
  src/mocks/handler/wordQuizGameHandler.ts
  src/pages/MiniGamePage/MiniGamePage.tsx
  src/shared/api/minigames.ts
Labels: 🐛 Fix

#91 [Fix] 초급 그래프 포인트 수정
  src/features/beginner_chart/model/store/graph.store.ts
  src/features/beginner_chart/model/store/quiz.store.ts
Labels: 🐛 Fix

#92 [Fix] 초급 그래프 포인트 api 받아오기 및 로직 수정3
  src/features/beginner_chart/model/store/graph.store.ts
  src/features/beginner_chart/model/store/quiz.store.ts
Labels: 🐛 Fix

#93 [Fix] 난이도별 낱말 퀴즈 조회 API 수정
  src/mocks/handler/wordQuizGameHandler.ts
  src/shared/api/minigames.ts
Labels: 🐛 Fix

#94 [Fix] 초급 그래프 포인트 api 받아오기 및 로직 수정4
  src/features/beginner_chart/model/store/graph.store.ts
  src/features/beginner_chart/model/store/quiz.store.ts
  src/pages/TradePages/BeginnerTradePage/QuizGraphPage.tsx
Labels: 🐛 Fix

#96 [Feat] 토큰 갱신 로직 구현
  src/entities/User/lib/tokenUtils.ts
  src/entities/User/model/store/authStore.ts
Labels: 🐛 Fix, ✨ Feature

#97 [Fix] 낱말 퀴즈 조회 버그 수정
  src/mocks/handler/wordQuizGameHandler.ts
  src/pages/MiniGamePage/WordQuizGamePage/WordQuizGamePage.tsx
  src/shared/api/minigames.ts
Labels: 🐛 Fix

#98 [Fix] 중급 그래프 매수 & 매도 창 변환
  src/features/Intermediate_chart/ui/StockSlider.tsx
Labels: 🔧 Chore, 📚 Docs, 💄 Style

#99 [Feat] 로그인된 사용자 리다이렉트 로직 수정
  src/app/router/PrivateRoute.tsx
  src/app/router/PublicRoute.tsx
  src/app/router/Router.tsx
Labels: 🐛 Fix, ✨ Feature

#100 [Fix] 중급 그래프 모달 수정
  src/features/Intermediate_chart/model/stock.ts
  src/features/Intermediate_chart/model/types/stock.ts
  src/features/Intermediate_chart/ui/StockSlider.tsx
  src/features/Intermediate_chart/ui/components/modals/BuyModal.tsx
  src/features/Intermediate_chart/ui/components/modals/CompletionModal.tsx
  src/features/Intermediate_chart/ui/components/modals/LimitModal.tsx
  src/features/Intermediate_chart/ui/components/modals/PointErrorModal.tsx
  src/features/Intermediate_chart/ui/components/modals/ResultModal.tsx
  src/features/Intermediate_chart/ui/components/modals/SellModal.tsx
  src/features/Intermediate_chart/ui/components/styles/StockSlider.tsx
  src/features/Intermediate_chart/ui/components/styles/index.ts
  src/features/Intermediate_chart/ui/index.ts
  src/pages/TradePages/IntermediateTradePage/IntermediatePage.tsx
Labels: 📚 Docs, 🐛 Fix

#101 [Fix] 중급 그래프 매도 오류1
  src/features/Intermediate_chart/model/stock.ts
  src/features/Intermediate_chart/model/types/stock.ts
  src/features/Intermediate_chart/ui/components/styles/StockSlider.tsx
Labels: 🐛 Fix

#104 [Fix] 회원가입 수정
  src/features/auth/signup/lib/signUpApi.ts
  src/features/auth/signup/lib/useJoin.ts
  src/features/auth/signup/lib/useSignUpForm.ts
  src/features/auth/signup/model/validation.ts
  src/features/auth/signup/ui/SignUpForm.tsx
Labels: 🐛 Fix, ✨ Feature

#105 [Fix] 고급 그래프 연결 수정
  package-lock.json
  package.json
  src/features/Advanced_chat/model/stockWebSocket.ts
  src/features/Advanced_chat/model/store/useAdvancedGameStore.ts
  src/features/Advanced_chat/types/game.ts
  src/features/Advanced_chat/types/stock.ts
  src/features/Advanced_chat/ui/StockSlider/stockSlider.tsx
  src/mocks/handler/advancedHandlers.ts
Labels: 🐛 Fix

#106 [Fix] 회원가입 수정
  src/entities/User/model/store/authStore.ts
  src/features/auth/signup/lib/signUpApi.ts
  src/features/auth/signup/lib/useJoin.ts
  src/features/auth/signup/ui/SignUpForm.tsx
Labels: 🐛 Fix

#107 [Fix] 고급 그래프 연결
  src/features/Advanced_chat/model/stockWebSocket.ts
Labels: 🐛 Fix

#108 [Modify] 회원가입시 리프레시 시도 로직 수정2
  src/features/auth/login/lib/setupInterceptors.ts
Labels: 🐛 Fix

#110 [Modify] 회원가입 수정
  src/app/providers/withAuth.tsx
Labels: 🐛 Fix

#111 [Fix] 고급 그래프 개발
  src/features/Advanced_chat/model/stockWebSocket.ts
  src/features/Advanced_chat/ui/StockSlider/stockSlider.tsx
Labels: 🐛 Fix

#112 Modify: 새로고침시 리프레쉬 안되는 로직 수정 #SCRUM-145
  src/app/providers/withAuth.tsx
Labels: 🐛 Fix

#115 [Modify] 마스킹 된 아이디를 서버에 직접 데이터 받아오도록 로직 수정
  src/features/auth/find_id_password/ui/AccountRecoveryForm.tsx
Labels: 🐛 Fix

#116 [Feat] 낱말 퀴즈 구현
  src/features/minigame/wordquizgame/model/wordQuizStore.ts
  src/features/minigame/wordquizgame/ui/Header.tsx
  src/mocks/handler/wordQuizGameHandler.ts
  src/pages/MiniGamePage/WordQuizGamePage/WordQuizGamePage.tsx
  src/shared/api/minigames.ts
  src/shared/api/wallets.ts
Labels: 🐛 Fix, ✨ Feature

#117 [Style] 아이디 데이터 받아오는 부분 글귀 수정
  src/features/auth/find_id_password/ui/MaskedIdModal.tsx
Labels: 💄 Style

#118 [Fix] 낱말 퀴즈 새로 시작 시 현재 단계와 목숨 수 초기화하도록 수정
  src/features/minigame/wordquizgame/model/wordQuizStore.ts
  src/pages/MiniGamePage/WordQuizGamePage/WordQuizGamePage.tsx
Labels: 🐛 Fix

#120 [Fix] 낱말 퀴즈 답안 제출 파트 수정
  src/mocks/handler/wordQuizGameHandler.ts
  src/pages/MiniGamePage/WordQuizGamePage/WordQuizGamePage.tsx
Labels: 🐛 Fix

#121 [Feat] 출석하기 구현
  src/features/mainpage/api/attendanceApi.ts
  src/features/mainpage/lib/queries.ts
  src/features/mainpage/model/types.ts
  src/features/mainpage/ui/AttendanceCard.tsx
  src/pages/mainpage/MainPage.tsx
Labels: ✨ Feature

#122 [Modify] 출석체크 로직 수정
  src/features/mainpage/api/attendanceApi.ts
  src/features/mainpage/lib/queries.ts
  src/features/mainpage/model/types.ts
  src/features/mainpage/ui/AttendanceCard.tsx
  src/pages/mainpage/MainPage.tsx
Labels: 🐛 Fix, ✨ Feature

#123 [Feat] 포인트 로드 구현 및 중복 에러 수정
  src/entities/User/model/types.ts
  src/features/mainpage/lib/queries.ts
  src/features/mainpage/ui/AttendanceCard.tsx
  src/features/mypage/ui/Profile.tsx
  src/pages/mainpage/MainPage.tsx
  src/shared/ui/PointBadge/PointBadge.tsx
Labels: 🐛 Fix, ✨ Feature

#124 [Modify] 출석체크 두번 요청되는 로직 수정
  src/features/mainpage/lib/queries.ts
Labels: 🐛 Fix

#125 [Modify] AttendanceCard에서만 출석 로직 구현되도록 수정
  src/features/mainpage/ui/AttendanceCard.tsx
  src/pages/mainpage/MainPage.tsx
Labels: 🐛 Fix

#128 [Fix] 검색 페이지 로직 수정
  src/features/search/api/userApi.ts
  src/features/search/lib/queries.ts
  src/features/search/model/types.ts
  src/features/search/ui/SearchResultList.tsx
Labels: 🐛 Fix

#129 [Modify] 검색 로직 오류 수정
  src/features/search/api/userApi.ts
  src/features/search/lib/queries.ts
  src/pages/searchPage/SearchPage.tsx
Labels: 🐛 Fix

#130 [Fix] 고급 그래프 수정
  src/features/Advanced_chat/model/stockWebSocket.ts
  src/features/Advanced_chat/types/stock.ts
  src/features/Intermediate_chart/ui/components/styles/StockSlider.tsx
Labels: 🐛 Fix

#131 [Fix] 고급 웹소켓WebSocketActions
  src/features/Advanced_chat/model/stockWebSocket.ts
Labels: 🐛 Fix

#132 [Fix] 문제 진행 시 게임 상태 표시 상단 바 수정
  src/features/minigame/wordquizgame/types/wordTypes.ts
  src/features/minigame/wordquizgame/ui/Header.tsx
  src/mocks/handler/wordQuizGameHandler.ts
  src/pages/MiniGamePage/MiniGamePage.tsx
  src/pages/MiniGamePage/WordQuizGamePage/WordQuizGamePage.tsx
  src/shared/api/minigames.ts
Labels: 🐛 Fix

#133 [Fix] 고급 그래프 수정
  src/features/Advanced_chat/model/store/useAdvancedGameStore.ts
Labels: 🐛 Fix

#134 [Fix] 고급 그래프 수정
  src/features/Advanced_chat/model/stockWebSocket.ts
  src/features/Advanced_chat/ui/StockSlider/stockSlider.tsx
Labels: 🐛 Fix

#135 [Fix] 고급 그래프 수정
  src/features/Advanced_chat/model/stockWebSocket.ts
Labels: 🐛 Fix

#137 [Fix] 정답 시 버그 수정
  src/mocks/handler/wordQuizGameHandler.ts
  src/pages/MiniGamePage/WordQuizGamePage/WordQuizGamePage.tsx
Labels: 🐛 Fix

#138 [Modify] 검색 실패시 Toast UI 안뜨도록 수정
  src/pages/searchPage/SearchPage.tsx
Labels: 🐛 Fix

#139 [Fix] 고급 그래프 수정
  src/features/Advanced_chat/model/stockWebSocket.ts
Labels: 🐛 Fix

#140 [Fix] 고급 그래프 수정
  src/features/Advanced_chat/model/stockWebSocket.ts
Labels: 🐛 Fix

#141 [Fix] 고급 그래프 수정
  src/features/Advanced_chat/model/stockWebSocket.ts
Labels: 🐛 Fix

#142 [Fix] 고급 그래프 수정
  src/features/Advanced_chat/model/stockWebSocket.ts
Labels: 🐛 Fix

#143 [Fix] 고급 그래프 WebSocket
  src/features/Advanced_chat/model/stockWebSocket.ts
Labels: 🐛 Fix

#144 고급 그래프 수정
  src/features/Advanced_chat/model/stockWebSocket.ts
Labels: 🐛 Fix

#146 [Fix] 고급 그래프 수정
  src/features/Advanced_chat/model/stockWebSocket.ts
Labels: 🐛 Fix

#147 [Fix] 계속 다음 문제로 넘어가는 오류 수정
  src/pages/MiniGamePage/WordQuizGamePage/WordQuizGamePage.tsx
Labels: 🐛 Fix

#148 [Fix] 게임 종료 로직 수정
  src/mocks/handler/wordQuizGameHandler.ts
  src/pages/MiniGamePage/WordQuizGamePage/WordQuizGamePage.tsx
  src/shared/api/minigames.ts
Labels: 🐛 Fix

#150 [Feat] 내 캐릭터 꾸미기 페이지 구현
  src/mocks/handler/avatarHandlers.ts
  src/mocks/handler/index.ts
  src/pages/AvatarPage/AvatarPage.tsx
  src/shared/api/avatar.ts
Labels: ✨ Feature

#153 [Fix] 고급 그래프 수정
  src/features/Advanced_chat/model/stockWebSocket.ts
Labels: 🐛 Fix

#154 [Fix] 3번째 문제 정답 시 버그 수정
  src/mocks/handler/wordQuizGameHandler.ts
  src/pages/MiniGamePage/WordQuizGamePage/WordQuizGamePage.tsx
  src/shared/api/minigames.ts
Labels: 🐛 Fix

#155 [Fix] 결과 페이지로 넘어가지 않는 버그 수정
  src/pages/MiniGamePage/WordQuizGamePage/WordQuizGamePage.tsx
Labels: 🐛 Fix

#157 [Feat] 친구목록 구현
  src/app/router/Router.tsx
  src/features/freind/api/friendApi.ts
  src/features/freind/lib/quries.ts
  src/features/freind/model/types.ts
  src/features/freind/ui/FriendList.tsx
  src/features/mypage/model/types.ts
  src/mocks/handler/friendHandlers.ts
  src/mocks/handler/index.ts
  src/pages/friendPage/FriendPage.tsx
  src/pages/mainpage/MainPage.tsx
  src/shared/config/index.ts
Labels: ✨ Feature

#160 [Fix] 고급 그래프 수정
  src/shared/api/advancedGame.ts
Labels: 🐛 Fix

#161 [Fix] WebSocket을 연결로직수정
  src/features/Advanced_chat/model/store/useAdvancedGameStore.ts
  src/features/Advanced_chat/ui/StockSlider/stockSlider.tsx
Labels: 🐛 Fix

#162 [Fix] 고급 그래프 수정
  src/features/Advanced_chat/model/stockWebSocket.ts
  src/features/Advanced_chat/types/stock.ts
  src/features/Intermediate_chart/ui/components/styles/StockSlider.tsx
  src/pages/TradePages/AdvancedTradePage/AdvancedTradePage.tsx
Labels: 🐛 Fix

#163 [Fix] 고급 그래프 수정
  src/features/Advanced_chat/model/stockWebSocket.ts
  src/features/Intermediate_chart/ui/components/styles/StockSlider.tsx
Labels: 🐛 Fix

#164 [Feat] 환전하기 구현
  src/features/exchange/ui/CurrentStatus.tsx
  src/features/minigame/points/types/pointTypes.ts
  src/pages/exchangePage/ExchangePage.tsx
Labels: ✨ Feature

#165 [Fix] 고급 그래프 구현
  src/features/Advanced_chat/model/stockWebSocket.ts
Labels: 🐛 Fix

#166 [Fix] 로그인 된 사용자 정보를 가져오도록 수정
  src/pages/exchangePage/ExchangePage.tsx
Labels: 🐛 Fix

#167 [Fix] 고급 주식 그래프
  src/features/Advanced_chat/model/stockWebSocket.ts
  src/features/Advanced_chat/model/store/useAdvancedGameStore.ts
  src/features/Intermediate_chart/ui/components/styles/StockSlider.tsx
Labels: 🐛 Fix

#168 [Fix] 고급 그래프 수정
  src/features/Advanced_chat/model/stockWebSocket.ts
  src/features/Intermediate_chart/ui/components/styles/index.ts
Labels: 🐛 Fix

#169 [Fix] 고급 웹소켓토큰 받아오기
  src/features/Advanced_chat/model/stockWebSocket.ts
Labels: 🐛 Fix

#170 [Fix] 고급 웹소켓토큰 받아오기
  src/features/Advanced_chat/model/stockWebSocket.ts
Labels: 🐛 Fix

#171 [Fix] 고급 웹소켓토큰 받아오기4
  src/features/Advanced_chat/model/stockWebSocket.ts
Labels: 🐛 Fix

#172 [Fix] 고급 웹소켓토큰 받아오기
  src/features/Advanced_chat/model/stockWebSocket.ts
Labels: 🐛 Fix

#175 [Fix] 초급 그래프 수정 & 포인트 작업
  src/features/Advanced_chat/model/stockWebSocket.ts
  src/features/beginner_chart/model/store/graph.store.ts
  src/features/beginner_chart/model/store/quiz.store.ts
  src/features/beginner_chart/ui/quiz-widget/QuizModal.tsx
  src/pages/TradePages/BeginnerTradePage/QuizGraphPage.tsx
Labels: 🐛 Fix

#178 [Feat] 랜딩페이지 구현
  src/app/layout/Layout.tsx
  src/app/router/Router.tsx
  src/pages/LandingPage/LandingPage.tsx
Labels: ✨ Feature

#180 [Fix] 초급그래프 포인트 로직
  src/features/beginner_chart/model/store/quiz.store.ts
Labels: 🐛 Fix

#181 [Feat] 내 캐릭터 꾸미기 페이지 구현
  src/mocks/handler/avatarHandlers.ts
  src/pages/AvatarPage/AvatarDetailPage.tsx
  src/pages/AvatarPage/AvatarPage.tsx
Labels: ✨ Feature

#183 [Chore] nginx.conf SSE 설정 추가
  nginx.conf
Labels: 🔧 Chore

#184 [Fix] 중급 그래프 수정
  src/features/Intermediate_chart/model/stock.ts
  src/features/Intermediate_chart/model/types/stock.ts
  src/features/Intermediate_chart/ui/components/modals/CompletionModal.tsx
  src/features/Intermediate_chart/ui/components/styles/StockSlider.tsx
  src/features/beginner_chart/model/store/quiz.store.ts
Labels: 🐛 Fix

#185 [Test] 아바타 구매를 위한 테스트 조건 추가
  src/features/mainpage/api/attendanceApi.ts
  src/features/minigame/flipcardgame/lib/useMiniGamePoints.ts
  src/pages/MiniGamePage/FlipCardGamePage/FlipCardGamePage.tsx
Labels: ✅ Test

#186 [Feat] 캐시 갱신 구현
  src/pages/MiniGamePage/WordQuizGamePage/WordQuizResultPage.tsx
Labels: ✨ Feature

#188 [Fix] 중급 그래프 수정
  src/features/Intermediate_chart/model/stock.ts
  src/features/Intermediate_chart/model/types/stock.ts
  src/features/Intermediate_chart/ui/components/modals/BuyModal.tsx
  src/features/Intermediate_chart/ui/components/modals/CompletionModal.tsx
  src/features/Intermediate_chart/ui/components/modals/ResultModal.tsx
  src/features/Intermediate_chart/ui/components/modals/SellModal.tsx
  src/features/Intermediate_chart/ui/components/modals/WarningModal.tsx
  src/features/Intermediate_chart/ui/components/styles/StockSlider.tsx
Labels: 🐛 Fix

#190 [Fix] 중급 그래프 중간 저장
  src/features/Intermediate_chart/model/stock.ts
  src/features/Intermediate_chart/ui/components/modals/BuyModal.tsx
  src/features/Intermediate_chart/ui/components/styles/StockSlider.tsx
Labels: 🐛 Fix

#191 [Fix] 중급 그래프 수정
  src/features/Intermediate_chart/model/stock.ts
  src/features/Intermediate_chart/ui/components/modals/CompletionModal.tsx
  src/features/Intermediate_chart/ui/components/modals/LimitModal.tsx
  src/features/Intermediate_chart/ui/components/modals/ResultModal.tsx
  src/features/Intermediate_chart/ui/components/modals/SellModal.tsx
  src/features/Intermediate_chart/ui/components/styles/StockSlider.tsx
Labels: 🐛 Fix

#192 [Fix] 중급 그래프 수정
  src/features/Intermediate_chart/ui/components/modals/WarningModal.tsx
  src/features/Intermediate_chart/ui/components/styles/StockSlider.tsx
Labels: 🐛 Fix

#193 [Fix] 중급 그래프 포인트 로직
  src/features/Intermediate_chart/ui/components/styles/StockSlider.tsx
Labels: 🐛 Fix

#194 [fix] 모달 창 수정
  src/features/Intermediate_chart/model/stock.ts
  src/features/Intermediate_chart/model/types/stock.ts
  src/features/Intermediate_chart/ui/components/modals/ErrorModal.tsx
  src/shared/api/stock.ts
Labels: 🐛 Fix

#195 [Fix] 중급 그래프 거래 제한 모달 창
  src/features/Intermediate_chart/ui/components/modals/ErrorModal.tsx
Labels: 🐛 Fix

#196 [fix] 고급 그래프 수정 반영
  src/features/Advanced_chat/model/stockWebSocket.ts
  src/features/Advanced_chat/ui/StockSlider/stockSlider.tsx
Labels: 🐛 Fix

#197 [Fix] 중급 포인트 확인
  src/features/Intermediate_chart/model/stock.ts
  src/features/Intermediate_chart/model/types/stock.ts
  src/features/Intermediate_chart/ui/components/modals/ErrorModal.tsx
  src/features/Intermediate_chart/ui/components/modals/TradeComponent.tsx
  src/features/Intermediate_chart/ui/components/styles/StockSlider.tsx
Labels: 🐛 Fix

#198 [Fix] 고급 웹소켓 헤더 방식으로변환
  src/features/Advanced_chat/model/stockWebSocket.ts
Labels: 🐛 Fix

#199 fix 고급 웹소켓 헤더 방식으로변환
  src/features/Advanced_chat/model/stockWebSocket.ts
Labels: 🐛 Fix

#200 [Fix] 고급 웹소켓 헤더 방식으로변환 누락파일
  src/features/Advanced_chat/ui/StockSlider/stockSlider.tsx
  src/shared/api/advancedGame.ts
Labels: 🐛 Fix

#201 [Fix] 고급 웹소켓리롤
  src/features/Advanced_chat/model/stockWebSocket.ts
  src/features/Advanced_chat/ui/StockSlider/stockSlider.tsx
  src/shared/api/advancedGame.ts
Labels: 🐛 Fix

#202 [Fix] 중급 모달창 수정
  src/features/Advanced_chat/model/stockWebSocket.ts
  src/features/Intermediate_chart/ui/components/modals/BuyModal.tsx
  src/features/Intermediate_chart/ui/components/modals/SellModal.tsx
  src/features/Intermediate_chart/ui/components/styles/index.ts
Labels: 🐛 Fix

#203 fix 중급 포인트 수정
  src/features/Intermediate_chart/model/stock.ts
  src/features/Intermediate_chart/ui/components/modals/ErrorModal.tsx
  src/features/Intermediate_chart/ui/components/styles/index.ts
Labels: 🐛 Fix

#204 [Fix] 중급 포인트2
  src/features/Intermediate_chart/ui/components/modals/BuyModal.tsx
  src/features/Intermediate_chart/ui/components/modals/ErrorModal.tsx
Labels: 🐛 Fix

#205 [Chore] nginx.conf 고급 모의투자 및 웹 소켓 설정
  nginx.conf
Labels: 🔧 Chore

#206 [Chore] nginx.conf 변수명 통일
  nginx.conf
Labels: 🔧 Chore

#207 [Fix] 고급 웹소켓 jwt 연결
  src/features/Advanced_chat/model/store/useAdvancedGameStore.ts
Labels: 🐛 Fix

#208 [Fix] 고급 웹소켓 jwt 수정
  src/features/Advanced_chat/model/store/useAdvancedGameStore.ts
Labels: 🐛 Fix

#210 [Fix] 중급 그래프 지갑 연동확인
  src/features/Intermediate_chart/model/stock.ts
  src/features/Intermediate_chart/ui/components/modals/BuyModal.tsx
  src/features/Intermediate_chart/ui/components/modals/ErrorModal.tsx
  src/features/Intermediate_chart/ui/components/modals/SellModal.tsx
  src/features/Intermediate_chart/ui/components/modals/TradeComponent.tsx
  src/features/Intermediate_chart/ui/components/styles/StockSlider.tsx
  src/mocks/handler/IntermediateHandlers.ts
Labels: 🐛 Fix

#211 [Fix] 중급 매도 부분 서버확인
  src/features/Intermediate_chart/model/stock.ts
Labels: 🐛 Fix

#212 [Fix] 중급 설계 미스 수정
  src/features/Intermediate_chart/ui/components/modals/BuyModal.tsx
  src/features/Intermediate_chart/ui/components/modals/SellModal.tsx
  src/features/Intermediate_chart/ui/components/styles/StockSlider.tsx
  src/features/Intermediate_chart/ui/components/styles/index.ts
Labels: 🐛 Fix

#213 [Fix] 중급 설계 미스 수정2
  src/features/Intermediate_chart/model/stock.ts
  src/features/Intermediate_chart/ui/components/modals/SellModal.tsx
  src/features/Intermediate_chart/ui/components/styles/StockSlider.tsx
Labels: 🐛 Fix

#214 [Feat] OX 퀴즈 구현
  src/app/layout/Layout.tsx
  src/app/providers/state/zustand/useOXQuizStore.ts
  src/app/router/Router.tsx
  src/features/minigame/oxquizgame/types/oxTypes.ts
  src/mocks/handler/index.ts
  src/mocks/oxQuizGameHandlers.ts
  src/pages/MiniGamePage/MiniGamePage.tsx
  src/pages/MiniGamePage/OXQuizGamePage/OXQuizGamePage.tsx
  src/pages/MiniGamePage/OXQuizGamePage/OXQuizResultPage.tsx
  src/pages/MiniGamePage/OXQuizGamePage/store/useOXQuizStore.ts
  src/shared/api/minigames.ts
Labels: ✨ Feature

#215 [Fix] 결과 오류 수정
  src/features/minigame/oxquizgame/types/oxTypes.ts
  src/mocks/oxQuizGameHandlers.ts
  src/pages/MiniGamePage/OXQuizGamePage/OXQuizGamePage.tsx
  src/pages/MiniGamePage/OXQuizGamePage/store/useOXQuizStore.ts
Labels: ✨ Feature

#216 [Fix] 중급 그래프 db 연동 수정
  src/features/Intermediate_chart/model/stock.ts
  src/features/Intermediate_chart/ui/components/modals/CompletionModal.tsx
  src/features/Intermediate_chart/ui/components/modals/ErrorModal.tsx
  src/features/Intermediate_chart/ui/components/modals/LimitModal.tsx
  src/features/Intermediate_chart/ui/components/modals/PointErrorModal.tsx
  src/features/Intermediate_chart/ui/components/modals/ResultModal.tsx
  src/features/Intermediate_chart/ui/components/modals/SellModal.tsx
  src/features/Intermediate_chart/ui/components/modals/TradeComponent.tsx
  src/features/Intermediate_chart/ui/components/modals/WarningModal.tsx
Labels: 🐛 Fix

#217 [Feat] OX 퀴즈 포인트 기능 구현
  src/pages/MiniGamePage/OXQuizGamePage/OXQuizResultPage.tsx
Labels: ✨ Feature

#218 [Fix] gameType 값 수정
  src/pages/MiniGamePage/OXQuizGamePage/OXQuizResultPage.tsx
Labels: 🐛 Fix

#219 [Fix] 중급그래프 db 연동 수정
  src/features/Intermediate_chart/ui/components/styles/StockSlider.tsx
Labels: 🐛 Fix

#220 [Feat] 알림 기능 구현
  public/img/3d-bell.png
  public/img/box-check.png
  src/app/App.tsx
  src/app/layout/Layout.tsx
  src/app/router/Router.tsx
  src/features/freind/api/friendApi.ts
  src/features/freind/lib/quries.ts
  src/features/freind/model/types.ts
  src/features/notification/api/notificationApi.ts
  src/features/notification/lib/queries.ts
  src/features/notification/lib/useNotificationSSE.ts
  src/features/notification/model/types.ts
  src/features/notification/ui/NotificationItem.tsx
  src/features/notification/ui/NotificationList.tsx
  src/mocks/handler/index.ts
  src/mocks/handler/notificationHandlers.ts
  src/pages/notificationPage/NotificationPage.tsx
  src/shared/config/index.ts
  src/widgets/Header/index.tsx
Labels: ✨ Feature

#221 [Fix] 미니게임 페이지 UI 수정
  src/features/mainpage/ui/AttendanceCard.tsx
  src/features/minigame/ui/AvatarCard.tsx
  src/features/minigame/ui/ExchangeCard.tsx
  src/pages/MiniGamePage/MiniGamePage.tsx
Labels: 🐛 Fix

#222 [Modify] 알림 데이터 오는지 콘솔로 확인
  src/features/notification/ui/NotificationList.tsx
Labels: 🐛 Fix

#223 [Feat] 친구 요청 api 추가 및 수정
  src/features/notification/api/notificationApi.ts
  src/features/notification/lib/queries.ts
  src/features/search/lib/queries.ts
Labels: 🐛 Fix, ✨ Feature

#224 [Modify] Response 키값 수정
  src/features/notification/api/notificationApi.ts
  src/features/search/lib/queries.ts
  src/features/search/ui/SearchResultList.tsx
  src/pages/searchPage/SearchPage.tsx
Labels: 🐛 Fix

#225 [Chore] 웹소켓 경로 수정
  nginx.conf
Labels: 🔧 Chore, 📚 Docs

#226 [Fix] 초급 그래프 포인트 연결 확인
  src/features/Advanced_chat/model/stockWebSocket.ts
  src/features/Intermediate_chart/ui/components/modals/BuyModal.tsx
  src/features/Intermediate_chart/ui/components/modals/ErrorModal.tsx
  src/features/Intermediate_chart/ui/components/modals/ResultModal.tsx
  src/features/Intermediate_chart/ui/components/modals/SellModal.tsx
  src/features/Intermediate_chart/ui/components/styles/StockSlider.tsx
  src/features/beginner_chart/model/api/graph.api.ts
  src/features/beginner_chart/model/store/graph.store.ts
  src/features/beginner_chart/model/store/quiz.store.ts
  src/features/beginner_chart/model/types/quiz.ts
  src/features/beginner_chart/ui/fast-graph/fast-graph.tsx
  src/features/beginner_chart/ui/quiz-widget/QuizModal.tsx
  src/mocks/handler/IntermediateHandlers.ts
  src/pages/TradePages/BeginnerTradePage/QuizGraphPage.tsx
  src/shared/api/stock.ts
Labels: 🐛 Fix

#227 [Fix] 초급그래프 api 연결 오류 확인
  src/features/beginner_chart/model/store/graph.store.ts
Labels: 🐛 Fix

#228 [Fix] 초급그래프 연결 오류 확인
  src/features/beginner_chart/model/api/graph.api.ts
  src/features/beginner_chart/model/store/graph.store.ts
  src/features/beginner_chart/model/store/quiz.store.ts
  src/features/beginner_chart/model/types/stock.ts
  src/features/beginner_chart/ui/fast-graph/fast-graph.tsx
  src/features/beginner_chart/ui/quiz-widget/QuizModal.tsx
  src/pages/TradePages/BeginnerTradePage/BeginnerTradePage.tsx
  src/pages/TradePages/BeginnerTradePage/QuizGraphPage.tsx
Labels: 🐛 Fix

#229 [Fix] 초급그래프 초기화
  src/features/beginner_chart/model/store/quiz.store.ts
Labels: 🐛 Fix

#230 [Modify] 친구 요청 상태 수정
  src/features/freind/api/friendApi.ts
  src/features/freind/lib/quries.ts
  src/features/freind/model/types.ts
  src/features/notification/model/types.ts
  src/features/notification/ui/NotificationItem.tsx
  src/features/notification/ui/NotificationList.tsx
Labels: 🐛 Fix

#231 [Fix] 초급 그래프 수정
  src/features/beginner_chart/model/store/graph.store.ts
  src/features/beginner_chart/model/store/quiz.store.ts
Labels: 🐛 Fix

#232 Feature/notification/scrum 164
  src/features/notification/ui/NotificationList.tsx
Labels: 🐛 Fix

#233 [Modify] 친구요청 보내기 ID 값 수정
  src/features/notification/ui/NotificationItem.tsx
Labels: 🐛 Fix

#234 [Chore] S3를 통한 프론트 배포 로직 구성
  .github/workflows/deploy-s3.yml
Labels: 🔧 Chore

#235 [Modify] 친구요청 / 알림 로직 변경 및 흐름 순서 변경
  src/features/notification/lib/queries.ts
  src/features/notification/ui/NotificationItem.tsx
  src/features/notification/ui/NotificationList.tsx
Labels: 🐛 Fix
