Repository prgrms-web-devcourse-final-project/WEB1_2_Child-Learn_FE, pull requests merged in 2024-11, with the labels that each got.

#10 [Feat] GNB구현
  public/img/bell.png
  public/img/brush.png
  public/img/chat.png
  public/img/close.png
  public/img/game.png
  public/img/home.png
  public/img/index.ts
  public/img/logo.png
  public/img/menu.png
  public/img/search.png
  public/img/user.png
  src/app/layout/Layout.tsx
  src/app/router/Router.tsx
  src/widgets/Footer/Footer.module.css
  src/widgets/Footer/index.tsx
  src/widgets/Header/Header.module.css
  src/widgets/Header/index.tsx
Labels: ✨ Feature

#11 [Docs] PR 템플릿 추가
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 📚 Docs

#12 [Feat] 초급 주식 프로그램 개발
  package-lock.json
  package.json
  public/img/coins.png
  public/img/imagex.jpg
  public/img/out.png
  src/app/App.tsx
  src/app/layout/Layout.tsx
  src/app/router/Router.tsx
  src/features/article/article.tsx
  src/features/article/pages/articlepage.tsx
  src/features/article/type/article.ts
  src/features/beginner_chat/pages/fastgraph.tsx
  src/features/beginner_chat/pages/quizpage.tsx
  src/features/beginner_chat/types/graph.ts
  src/features/beginner_chat/types/quiz.ts
  src/features/beginner_chat/types/stock.ts
  src/features/beginner_chat/ui/quizcard.tsx
  tsconfig.app.json
  tsconfig.node.json
  vite.config.ts
Labels: ✨ Feature

#15 [Feat] 로그인 페이지 구현
  public/img/google-btn.png
  public/img/kakao-btn.png
  public/img/naver-btn.png
  src/app/layout/Layout.tsx
  src/app/router/Router.tsx
  src/features/LoginForm/lib/validation.ts
  src/features/LoginForm/model/index.tsx
  src/features/LoginForm/ui/LoginForm.tsx
  src/features/auth/login/lib/useLoginForm.ts
  src/features/auth/login/model/store.ts
  src/features/auth/login/ui/LoginForm.tsx
  src/features/beginner_chat/pages/fastgraph.tsx
  src/pages/HomePage/HompPage.tsx
  src/pages/LandingPage/LandingPage.tsx
  src/pages/auth/login/LoginPage.tsx
  src/pages/postPage/index.tsx
  src/shared/ui/AuthButton/AuthButton.tsx
  src/shared/ui/AuthInput/AuthInput.tsx
  src/shared/ui/index.ts
  tsconfig.app.json
  vite.config.ts
Labels: ✨ Feature

#17 [Feat] 회원가입 페이지 폼 구현
  src/app/layout/Layout.tsx
  src/app/router/Router.tsx
  src/features/CommentSection/model/index.ts
  src/features/CommentSection/ui/index.ts
  src/features/auth/signup/lib/useSignUpForm.ts
  src/features/auth/signup/ui/SignUpForm.tsx
  src/pages/auth/signup/SignUpPage.tsx
Labels: ✨ Feature

#20 [Feat] 메인 페이지 구현
  public/img/3d-graph.png
  public/img/boy.png
  public/img/calculator.png
  public/img/calendar.png
  public/img/chess.png
  public/img/coins.png
  public/img/contract.png
  public/img/flower.png
  public/img/gift.png
  public/img/lightbulb.png
  public/img/lock.png
  public/img/magic-hat.png
  public/img/money.png
  public/img/palette.png
  public/img/trophy.png
  src/app/router/Router.tsx
  src/features/mainpage/ui/AttendanceCard.tsx
  src/features/mainpage/ui/DifficultyModal.tsx
  src/mocks/handler/authHandlers.ts
  src/mocks/handler/postHandlers.ts
  src/mocks/handler/userHandlers.ts
  src/pages/HomePage/HompPage.tsx
  src/pages/mainpage/MainPage.tsx
  src/shared/ui/InfoCard/InfoCard.tsx
  src/shared/ui/MenuCard/MenuCard.tsx
  src/shared/ui/PointBadge/PointBadge.tsx
  src/widgets/Footer/index.tsx
  src/widgets/Header/index.tsx
Labels: ✨ Feature

#26 [Feat] 낱말 퀴즈 구현
  public/img/heart-icon-empty.png
  public/img/heart-icon.png
  src/app/layout/Layout.tsx
  src/features/minigame/wordquizgame/model/wordQuizStore.ts
  src/features/minigame/wordquizgame/types/wordTypes.ts
  src/features/minigame/wordquizgame/ui/Answer.tsx
  src/features/minigame/wordquizgame/ui/Header.tsx
  src/features/minigame/wordquizgame/ui/KeyBoard.tsx
  src/features/minigame/wordquizgame/ui/Popup.tsx
  src/features/minigame/wordquizgame/ui/Question.tsx
  src/pages/MiniGamePage/MiniGamePage.tsx
  src/pages/MiniGamePage/WordQuizGamePage/WordQuizGamePage.tsx
  src/pages/MiniGamePage/WordQuizGamePage/WordQuizResultPage.tsx
  src/pages/MiniGamePage/WordQuizGamePage/store/useWordQuizStore.ts
Labels: ✨ Feature

#29 [Feat] 중급 그래프 개발
  package-lock.json
  package.json
  public/img/arrow.png
  public/img/arrow2.png
  public/img/article.png
  public/img/graph1.png
  public/img/minus.png
  public/img/plus.png
  src/app/layout/Layout.tsx
  src/app/router/Router.tsx
  src/entities/ article/types/article.ts
  src/entities/ article/ui/ArticleComponent.tsx
  src/entities/stock/model/stock.ts
  src/entities/stock/types/index.ts
  src/entities/stock/types/stock.ts
  src/entities/stock/ui/StockCard/card.tsx
  src/features/Intermediate_chat/model/stock.ts
  src/features/Intermediate_chat/types/stock.ts
  src/features/Intermediate_chat/ui/StockSlider.tsx
  src/features/Intermediate_chat/ui/index.ts
  src/features/beginner_chat/model/store/graph.store.ts
  src/features/beginner_chat/model/types/graph.ts
  src/features/beginner_chat/model/types/quiz.ts
  src/features/beginner_chat/model/types/stock.ts
  src/features/beginner_chat/ui/fast-graph/fast-graph.tsx
  src/features/beginner_chat/ui/fast-navgation/fast-navigation.tsx
  src/features/beginner_chat/ui/quiz-widget/quizcard.tsx
  src/features/beginner_chat/ui/quiz-widget/quizpage.tsx
  src/main.tsx
  src/mocks/browser.ts
  src/mocks/handler/IntermediateHandlers.ts
  src/mocks/index.ts
  src/pages/TradePages/IntermediateTradePage/IntermediatePage.tsx
  src/shared/api/stock.ts
  src/shared/ui/Dialog/Dialog.tsx
  src/shared/ui/Intermediate/StockChat.tsx
  src/shared/ui/chat_Input/Input.tsx
  src/shared/ui/config/constants.ts
Labels: ✨ Feature

#30 Feat: 중급 그래프 완료
  src/entities/article/types/article.ts
  src/entities/article/ui/ArticleComponent.tsx
Labels: ✨ Feature

#32 [Feat] 로그인 기능 구현
  package-lock.json
  package.json
  src/app/App.tsx
  src/app/layout/Layout.tsx
  src/app/providers/withAuth.tsx
  src/app/providers/withCookie.tsx
  src/app/providers/withQuery.tsx
  src/entities/User/model/index.ts
  src/entities/User/model/store/authStore.ts
  src/entities/User/model/types.ts
  src/features/auth/login/lib/loginApi.ts
  src/features/auth/login/lib/queries.ts
  src/features/auth/login/lib/setupInterceptors.ts
  src/features/auth/login/lib/useLoginForm.ts
  src/features/auth/login/model/store.ts
  src/features/auth/login/model/types.ts
  src/features/auth/login/model/useLogin.ts
  src/features/auth/login/ui/LoginForm.tsx
  src/features/auth/signup/lib/signUpApi.ts
  src/main.tsx
  src/mocks/handler/index.ts
  src/mocks/handler/loginHandlers.ts
  src/mocks/handler/signUpHandlers.ts
  src/pages/auth/login/LoginPage.tsx
  src/shared/api/base.ts
  src/shared/config/index.ts
  src/shared/lib/index.ts
  src/shared/lib/toast/index.ts
  src/shared/lib/token/index.ts
Labels: ✨ Feature

#34 [Feat] 로그인 상태 관리 구현
  src/app/App.tsx
  src/app/router/Router.tsx
  src/entities/Post/model/index.ts
  src/entities/Post/ui/index.ts
  src/entities/User/api/userApi.ts
  src/entities/User/lib/queries.ts
  src/entities/User/model/types.ts
  src/features/auth/login/lib/queries.ts
  src/features/auth/login/lib/setupInterceptors.ts
  src/mocks/browser.ts
  src/mocks/handler/index.ts
  src/mocks/handler/loginHandlers.ts
  src/mocks/handler/loginUserHandlers.ts
  src/mocks/index.ts
  src/pages/MiniGamePage/MiniGamePage.tsx
  src/pages/mainpage/MainPage.tsx
  src/shared/ui/PointBadge/PointBadge.tsx
Labels: ✨ Feature

#37 [Feat] 아이디 / 비밀번호 찾기 구현
  src/app/layout/Layout.tsx
  src/app/router/Router.tsx
  src/features/auth/find_id_password/api/accountRecovery.ts
  src/features/auth/find_id_password/lib/queries.ts
  src/features/auth/find_id_password/model/types.ts
  src/features/auth/find_id_password/ui/AccountRecoveryForm.tsx
  src/features/auth/find_id_password/ui/AccountRecoveryTabs.tsx
  src/features/auth/find_id_password/ui/MaskedIdModal.tsx
  src/features/auth/find_id_password/ui/ResetPasswordModal.tsx
  src/features/auth/login/ui/LoginForm.tsx
  src/mocks/handler/findIdHandlers.ts
  src/mocks/handler/index.ts
  src/pages/auth/find-id-password/AccountRecoveryPage.tsx
  src/shared/config/index.ts
Labels: ✨ Feature

#40 [Fix] 회원가입 생년월일 입력시 DB 저장값 수정
  src/features/auth/signup/model/types.ts
  src/features/auth/signup/ui/SignUpForm.tsx
Labels: 🐛 Fix

#44 [Fix] 로그인 로직 수정
  src/features/auth/login/lib/setupInterceptors.ts
Labels: 🐛 Fix

#45 [Feat] 마이페이지 구현
  public/img/basic-profile.png
  public/img/clock.png
  public/img/coin-icon.png
  public/img/megaphone.png
  public/img/question-mark.png
  public/img/shopping.png
  public/img/user-icon.png
  public/img/wallet.png
  src/app/router/Router.tsx
  src/entities/User/model/types.ts
  src/features/mypage/api/logoutApi.ts
  src/features/mypage/lib/queries.ts
  src/features/mypage/model/types.ts
  src/features/mypage/ui/Character.tsx
  src/features/mypage/ui/MenuList.tsx
  src/features/mypage/ui/Profile.tsx
  src/features/mypage/ui/UserPoints.tsx
  src/mocks/handler/loginUserHandlers.ts
  src/pages/myPage/MyPage.tsx
  src/shared/config/index.ts
  src/widgets/Footer/index.tsx
Labels: ✨ Feature

#47 [Fix] 유저 데이터 로직 수정
  src/entities/User/api/userApi.ts
Labels: 🐛 Fix
